version: '2'

services:
  webserver:
    container_name: bus_webserver
    build: .
    ports:
      - 8099:80
    depends_on:
      - database-bus
    user: "${UID}:${GID}"
    volumes:
      - .:/var/www
      - ./public:/var/www/html
#    environment:
#      - 'XDEBUG_CONFIG=remote_host=192.168.56.1'

  database-bus:
    image: mysql
    container_name: mysql-database-bus
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./db/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=bus_DB
      - MYSQL_USER=hussain
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root
